all: make

edit:
	./edit.bash

lint:
	./lint.bash

make:
	./make.bash

mrun:
	./mrun.bash

test:
	./test.bash

vend:
	./vend.bash

clean:
	find . -type d -name "bin" -or -name "pkg" | xargs rm -rf
	find . -type f -name "*.local" | xargs rm -rf
